services:
    nginx:
        restart: always
        image: nginx:$VERSION_NGINX
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./acme.sh:/etc/nginx/certs
            - ./acme.sh/.well-known:/tmp/.well-known/
            - ./nginx/conf.d:/etc/nginx/conf.d/
            - ./nginx/dhparam.pem:/etc/nginx/dhparam.pem
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/snippets:/etc/nginx/snippets
            - ./nginx/logs:/var/log/nginx
            - ./nginx/template-variables:/etc/nginx/templates/10-variables.conf.template:ro
        depends_on:
            - whoami
        environment:
            - MYDOMAINNAME

    whoami:
        restart: always
        image: traefik/whoami
        hostname: whoami

    acme.sh:
        restart: always
        image: neilpang/acme.sh:latest
        volumes:
            - ./acme.sh:/acme.sh
        command: daemon

